### ISSUE TITLE
How use plugin with ajax?

### ISSUE THREAD

**Issue by cawa-93** [malihu/malihu-custom-scrollbar-plugin#346]
Code example:
```html
<button>Load</button>
<div id="ajaxContent"></div>
<div id="staticContent">
<!-- some html -->
</div>
<script>
$("#ajaxContent, #staticContent").mCustomScrollbar({
			axis: 'y',
			autoHideScrollbar: true,
			alwaysShowScrollbar: 0,
			contentTouchScroll: false,
			theme: "dark-thin",
			scrollbarPosition: 'inside',
			scrollInertia: 150,
			live: true,
			keyboard: {
				enable: false
			},
			mouseWheel: {
				scrollAmount: 61
			},
			advanced: {
				updateOnContentResize: true
			});
$('button').click(function(){
    $('#ajaxContent').load('ajax.php')
})
</script>
```
In #staticContent everything works. But in #ajaxContent after download the content the plugin does not work - displays a standard scrollbar.

Tried to use update method
```javascript
$('button').click(function(){
    $('#ajaxContent').load('ajax.php',function(){
        $("#ajaxContent").mCustomScrollbar("update");
    });
})
```
But it gave absolutely no effect

**Comment by malihu** [comment]
Hi, 

Since the element is already on the page when loading its content, you need to change: 
`$('#ajaxContent').load('ajax.php')`
to: 
`$('#ajaxContent .mCSB_container').load('ajax.php')`

For the same reason, you probably don't need the `live` option, so you can remove it.

Ref: http://manos.malihu.gr/jquery-custom-content-scroller/4/#faq-4
