### ISSUE TITLE
Nesting multiple scrollbars one inside another

### ISSUE THREAD

**Issue by Zusurs** [malihu/malihu-custom-scrollbar-plugin#369]
As far as I know in year 2012 somebody already asked about the nested scrollbar functionality. Is this function available as for now?

**Comment by malihu** [comment]
Nesting scrollbars is available since before version 3 (years ago). Plugin archive contains such examples and you can see some below: 
* [nested_scrollbars_demo.html](http://manos.malihu.gr/repository/custom-scrollbar/demo/examples/nested_scrollbars_demo.html)
* [nested_scrollbars_demo_alt.html](http://manos.malihu.gr/repository/custom-scrollbar/demo/examples/nested_scrollbars_demo_alt.html)
* [nested_scrollbars_demo_alt_2.html](http://manos.malihu.gr/repository/custom-scrollbar/demo/examples/nested_scrollbars_demo_alt_2.html)

**Comment by Zusurs** [comment]
Oh, thank you.
