### ISSUE TITLE
Update after applying CSS Zoom changes

### ISSUE THREAD

**Issue by ekaratzaferis** [malihu/malihu-custom-scrollbar-plugin#372]
Hi, 

I'm applying the custom scrollbar on the body [ .mCustomScrollbar() ], which contains a div with a height of 1200px, and everything works fine since the body has height 100%.

Somewhere in my code, I'm transforming (zoom-out) this div and then I'm calling this method: $('body').mCustomScrollbar('update').

The div acquires a new height value (let's say 1000px) but the scrollbar still allows me to scroll further down than the new height of the div.

Am I missing something here? Shouldn't the scrollbar autoadjust to the new height value?

**Comment by malihu** [comment]
Hello, 

Normally, you wouldn't have to call the update method at all (it should auto-update itself). 
Do you "zoom-out" via CSS scale transform (e.g. `transform:scale(.5,.5);`)?

**Comment by malihu** [comment]
Hey I did some tests and I think I get what the issue is. You haven't missed anything... This happens due to the way the plugin works and the way jQuery functions not accounting CSS scaling when calculating the height of objects. 

You can apply a workaround to do what you need, but it requires some extra code and a couple of CSS: 

1. 
The transformed element has to have `transform-origin: top;` in its style. 

2. 
You need to set plugin's content wrapper CSS overflow property to visible (add `!important` if needed): 
`.mCSB_container{ overflow: visible; }`

3. 
In the script/event where you apply the transformation, you need to add the following code **after** the CSS transform is set (via class, directly in css etc.): 
```
var elem=$("#your-div-id"),scaledHeight=elem[0].getBoundingClientRect().height;
elem.parents(".mCSB_container").css({
	"height": elem.outerHeight()!==scaledHeight ? scaledHeight : "auto"
});
```
changing `your-div-id` to the 1200px div id attribute. 

That's about it. I know it's not simple but there's no other way (at least for now). Depending on how complicated your markup/web app is, this might not be 100% what you need.

**Comment by ekaratzaferis** [comment]
I can't thank you enough!! 

Not only you replied so fast, but you also gave a solution! I used your code and now it properly resizes!

Again, thank you very much!

**Comment by azeemtoor** [comment]
Thanks malihu!
It helped me too.
