### ISSUE TITLE
scrollTo is not always executed properly

### ISSUE THREAD

**Issue by gessulatgessulat** [malihu/malihu-custom-scrollbar-plugin#380]
Hi malihu,

i think there is an issue with the proper execution of the scrollTo method.

I trigger the method when an input element is focused.
If i focus an input by clicking it only the first time the scrollTo is working.
If i use tab to focus the next input it seems to work but sometimes it also fails.

Example:
http://jsfiddle.net/3xg9w2o5/14/

Thanks

**Comment by malihu** [comment]
Hello, 

The way your app works, you don't have to disable `autoScrollOnFocus` option, so you can remove `advanced:{ autoScrollOnFocus: false },` from the function call. 

I think that the `focusin` event has some native delay which is greater(?) than 60 milliseconds (which is the default delay for scrollTo method). I'll have to check further of course what exactly happens between `focusin`, the method etc. (when I click an input and switch from another browser tab back to the fiddle tab, it does scroll). 

Anyway, you could normally solve the issue by either increasing the method's default timeout: 

`$(".scroll").mCustomScrollbar('scrollTo', actPos, {timeout:100});`

or using both `focusin` and `click` events on inputs: 

```
$(".scroll input, .scroll textarea, .scroll select").on("focusin click",function(event){
    // your code...
    $(".scroll").mCustomScrollbar('scrollTo', actPos<0 ? 0 : actPos ); //don't scroll below zero!
});
```

In either case, use `actPos<0 ? 0 : actPos` (instead of `actPos`) as the position parameter to avoid negative scroll-to numbers. 

Hope this helps

PS. I didn't experience the tab-focus fail at all...

**Comment by gessulatgessulat** [comment]
Hi,
thank you for your fast response.
The timeout option works great. Didn't expected that.

Thanks
