### ISSUE TITLE
Direction:RTL handling

### ISSUE THREAD

**Issue by shamsy** [malihu/malihu-custom-scrollbar-plugin#82]
Hi Malihu,
great plugin! one of the best so far on the web.
I've using it in an English version of a website, but when I tried to use it in the Arabic version, I still get the dragger aligned to the left and the whole scrollbar is shifted to the right.

Please try to change the direction to RTL to see what I'm talking about. I tried to hack the code by changing the configuration and inverting right and left floating and alignment without success.

I can pay you for the fix if you want to.

Thank you.
Shams

**Comment by ARMBouhali** [comment]
I've a wordpress template using the 3.1.11 version of you script.

I think The problem is not in CSS since the elements in RTL position should be displayed from right to left, by 'RTLizing' the inner content of the scrolling area. The scrollbar display on the right side should not be wrong at all.

However the control itself in non-touchscreen devices is messy. When pointing inside our scroll container  :
* In LTR : a scroll-down is interpreted as a scroll-right (using some javascript code), and a scroll-up is interpreted as a scroll-left. That's well done
* In RTL : a scroll-down should be interpreted as a scroll-left (because the first content is intuitively on the right side and the last on the left) which is actually manage in same way as LTR.

Can you tell us how to correct this or how to change this specific scroll interpretation instead of waiting for a new version.

B.Regards
Raouf

**Comment by malihu** [comment]
If you referring to the mouse-wheel behavior, you could use the `invert` option parameter to invert mouse-wheel scrolling direction: 
`mouseWheel:{ invert: true }`

Is this what you need?

**Comment by ARMBouhali** [comment]
yes that's it. I just tried to change it and it worked as expected
Thanks :)

**Comment by seobomj** [comment]
Hello! How to make a reverse without using dir = "rtl" or direction: rtl; ? It is necessary that the slider and content moving in the same direction.
Example: https://codepen.io/patrikhjelm/pen/klcnj (right block)
